id = "tree-sitter-query"
name = "Tree Sitter query"
description = "Support for tree-sitter query files (*.scm)"
version = "0.0.2"
schema_version = 1
authors = ["Vitaly Slobodin <vitaliy.slobodin@gmail.com>"]
repository = "https://github.com/vitallium/zed-tree-sitter-query"

[grammars.query]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-query"
commit = "60e253d3c9d6b1131a0f75c85e4bdcc9a48d5b42"
